// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TodoApi.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Todo Api")]
    public partial class TodoApiFeature
    {
        
        private Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "TodoApi.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Todo Api", "A basic todo api", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get all open items")]
        public async System.Threading.Tasks.Task GetAllOpenItems()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Get all open items", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                Reqnroll.Table table1 = new Reqnroll.Table(new string[] {
                            "Id",
                            "Title",
                            "Text",
                            "CreatedAt",
                            "UpdatedAt",
                            "Completed",
                            "CompletedAt"});
                table1.AddRow(new string[] {
                            "1",
                            "Test",
                            "Test2",
                            "2024-08-27T07:44:56.837",
                            "",
                            "false",
                            ""});
                table1.AddRow(new string[] {
                            "2",
                            "Test",
                            "Test2",
                            "2024-08-27T07:44:56.837",
                            "",
                            "true",
                            ""});
#line 5
        await testRunner.GivenAsync("the following todo items are in the database", ((string)(null)), table1, "Given ");
#line hidden
#line 9
        await testRunner.WhenAsync("I call GET endpoint /todo/open", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
        await testRunner.ThenAsync("the returned response status code is 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
        await testRunner.AndAsync("the returned response is", "[\r\n    {\r\n    \"id\": 1,\r\n    \"title\": \"Test\",\r\n    \"text\": \"Test2\",\r\n    \"createdA" +
                        "t\": \"2024-08-27T07:44:56.837\",\r\n    \"updatedAt\": null,\r\n    \"completed\": false,\r" +
                        "\n    \"completedAt\": null\r\n    }\r\n]", ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add a new todo item")]
        public async System.Threading.Tasks.Task AddANewTodoItem()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Add a new todo item", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
        await testRunner.WhenAsync("I call POST endpoint /todo/add with payload", "{\r\n    \"title\": \"d60653f3-c0a9-4063-8a24-81e7b48f4304\",\r\n    \"text\": \"b037a730-2e" +
                        "2d-46cd-b59e-62f5626d79be\"\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
        await testRunner.ThenAsync("the returned response status code is 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table2 = new Reqnroll.Table(new string[] {
                            "Title",
                            "Text",
                            "Completed"});
                table2.AddRow(new string[] {
                            "d60653f3-c0a9-4063-8a24-81e7b48f4304",
                            "b037a730-2e2d-46cd-b59e-62f5626d79be",
                            "false"});
#line 35
        await testRunner.AndAsync("the following todo item exists in the database", ((string)(null)), table2, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update existing todo item")]
        public async System.Threading.Tasks.Task UpdateExistingTodoItem()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Update existing todo item", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                Reqnroll.Table table3 = new Reqnroll.Table(new string[] {
                            "Id",
                            "Title",
                            "Text",
                            "CreatedAt",
                            "UpdatedAt",
                            "Completed",
                            "CompletedAt"});
                table3.AddRow(new string[] {
                            "1",
                            "Test",
                            "Test2",
                            "2024-08-27T07:44:56.837",
                            "",
                            "false",
                            ""});
#line 40
        await testRunner.GivenAsync("the following todo items are in the database", ((string)(null)), table3, "Given ");
#line hidden
#line 43
          await testRunner.WhenAsync("I call PUT endpoint /todo/update/1 with payload", "{\r\n  \"title\": \"bbf88146-8aed-4fd3-8022-9b019ffd41d4\",\r\n  \"text\": \"0b1dfa15-6dca-4" +
                        "49d-acf7-a905d4be2549\"\r\n}          ", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
        await testRunner.ThenAsync("the returned response status code is 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table4 = new Reqnroll.Table(new string[] {
                            "Title",
                            "Text",
                            "Completed"});
                table4.AddRow(new string[] {
                            "bbf88146-8aed-4fd3-8022-9b019ffd41d4",
                            "0b1dfa15-6dca-449d-acf7-a905d4be2549",
                            "false"});
#line 51
        await testRunner.AndAsync("the following todo item exists in the database", ((string)(null)), table4, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
